<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EXIPC0200" failures="1" tests="3" name="com.qa.testClass.LoginPageTest" time="62.090" errors="0" timestamp="2024-10-01T19:09:23 IST" skipped="0">
  <testcase classname="com.qa.testClass.LoginPageTest" name="invalidEmailErrText" time="11.491">
    <failure message="expected [Email address not found.] but found [Email address not found.anc]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Email address not found.] but found [Email address not found.anc]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.qa.testClass.LoginPageTest.invalidEmailErrText(LoginPageTest.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </failure>
    <system-out>
      <![CDATA[This is the Screenshot of failed test cases
<a href='D:\Eclipse-WorkSpace\SmartACProAppWithParallelExecution1server\FailedCasesScreenShots\Android_Pixel_8\2024-10-01-19-08-04\LoginPageTest\invalidEmailErrText.png'> <img src='D:\Eclipse-WorkSpace\SmartACProAppWithParallelExecution1server\FailedCasesScreenShots\Android_Pixel_8\2024-10-01-19-08-04\LoginPageTest\invalidEmailErrText.png' height='100' width='100'/> </a>]]>
    </system-out>
  </testcase> <!-- invalidEmailErrText -->
  <testcase classname="com.qa.testClass.LoginPageTest" name="invalidPasswordErrText" time="21.016"/>
  <testcase classname="com.qa.testClass.LoginPageTest" name="validLogin" time="29.583"/>
  <system-out>
    <![CDATA[This is the Screenshot of failed test cases
<a href='D:\Eclipse-WorkSpace\SmartACProAppWithParallelExecution1server\FailedCasesScreenShots\Android_Pixel_8\2024-10-01-19-08-04\LoginPageTest\invalidEmailErrText.png'> <img src='D:\Eclipse-WorkSpace\SmartACProAppWithParallelExecution1server\FailedCasesScreenShots\Android_Pixel_8\2024-10-01-19-08-04\LoginPageTest\invalidEmailErrText.png' height='100' width='100'/> </a>]]>
  </system-out>
</testsuite> <!-- com.qa.testClass.LoginPageTest -->
